#
# Copyright 2015, Wink Saville
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.

apps-$(CONFIG_APP_HW) += hw

# Libraries needed
hw-y = libsel4 libsel4_gen libsel4_putchar libsel4_halt

hw: kernel_elf $(hw-y)
